import './style.css';

const races = ['Humano', 'Elfo', 'Anão', 'Halfling', 'Tiefling', 'Meio-Elfo'];
const colors = ['#161513', '#412816', '#71461d', '#c9c7d2', '#a2342b', '#e8b653'];
const swatches = (items, selected, round='') => items.map((c,i)=>`<button class="${round} ${i===selected?'selected':''}" style="background:${c}">${i===selected?'✓':''}</button>`).join('');
const choice = (vals,on) => vals.map((v,i)=>`<button class="${i===on?'selected':''}">${v}</button>`).join('');
const group = (icon,title,body) => `<div class="group"><h4><span>${icon}</span>${title}</h4><div class="opts">${body}</div></div>`;

document.querySelector('#root').innerHTML = `<main class="page">
<header class="hero-head"><div class="brand"><div class="sigil">✡</div><div><span>CRIADOR DE</span><h1>PERSONAGEM</h1><p>Monte seu herói e viva grandes aventuras!</p></div><div class="twinkle">✦</div></div><div class="actions"><button class="ghost">↻ REINICIAR</button><button class="primary">▣ SALVAR FICHA</button></div></header>
<div class="workspace"><aside class="steps">${[['1','RAÇA','Escolha sua origem','🐺'],['2','CLASSE','Escolha sua profissão','⚔️'],['3','APARÊNCIA','Defina sua aparência','🎭'],['4','HISTÓRIA','Conte um pouco sobre você','📖']].map((s,i)=>`<div class="step ${i===0?'active':''}"><div class="medal">${s[3]}</div><strong>${s[0]}</strong><h3>${s[1]}</h3><p>${s[2]}</p></div>`).join('')}<div class="tip">☆ <b>DICA DO MESTRE</b><p>Suas escolhas definem quem você é e como o mundo verá o seu herói!</p></div></aside>
<section class="panel race"><h2>✦ 1. ESCOLHA SUA RAÇA ✦</h2><p>Cada raça possui habilidades únicas.</p><div class="cards">${races.map((r,i)=>`<article class="race-card ${r==='Elfo'?'selected':''}"><div class="portrait p${i}"></div><span>${r}</span><em>${r==='Elfo'?'✓':''}</em></article>`).join('')}</div><div class="info"><h3>🌿 ELFO</h3><p>Graciosos e ligados à natureza, os elfos são ágeis, sábios e possuem sentidos aguçados.</p><b>Vantagens:</b><ul><li>Visão no escuro</li><li>Percepção aguçada</li><li>Afinidade com a natureza</li></ul></div><button class="next">PRÓXIMA: ESCOLHA SUA CLASSE →</button></section>
<section class="preview"><h2>🛡️ SEU PERSONAGEM</h2><div class="forest"><div class="elf"><div class="head"></div><div class="cape"></div><div class="body"></div><div class="bow"></div><div class="legs"></div></div></div><div class="rotate">GIRAR&nbsp;&nbsp;‹ &nbsp;↻&nbsp; →</div></section>
<section class="panel appear"><h2>✦ 3. APARÊNCIA ✦</h2><p>Escolha como seu herói será.</p>${group('🎨','TOM DE PELE',swatches(['#efc58e','#c99057','#8b5d3b','#50301f'],2))}${group('💇','CABELO',['curto','franja','longo','coque','raspado'].map((h,i)=>`<button class="mini hair h${i} ${i===2?'selected':''}"></button>`).join(''))}${group('💧','COR DO CABELO',swatches(colors,3))}${group('👁️','COR DOS OLHOS',swatches(['#8b4f16','#5f8a42','#4d93b9','#585858','#83519d'],1,'round'))}${group('📏','ALTURA',choice(['▮','▮','▮'],1))}${group('✿','TIPO FÍSICO',choice(['▮','▮','▮','▮'],1))}${group('✴','MARCAS E DETALHES',choice(['⊘','╱','☠','∴','♧'],1))}${group('○','ACESSÓRIOS',choice(['⊘','♙','♧','〰','∞'],1))}${group('🧥','ROUPA / ESTILO',choice(['🧝','🥷','🧙','🧥','🕵'],0))}</section>
<aside class="sheet"><div class="ribbon">FICHA DO AVENTUREIRO</div><div class="row"><label>NOME DO PERSONAGEM<b>Lirien</b></label><label>JOGADOR<b>Maria Eduarda</b></label></div><div class="badges"><div>🌿<span>RAÇA<b>Elfo</b></span></div><div>🏹<span>CLASSE<b>Arqueiro</b></span></div></div><h3>✧ ATRIBUTOS ✧</h3><div class="attrs">${[['FORÇA','✊','3','+0'],['DESTREZA','🍃','5','+3'],['INTELIGÊNCIA','📖','3','+0'],['SABEDORIA','👁️','4','+1']].map(a=>`<div><span>${a[1]}</span><small>${a[0]}</small><b>${a[2]}</b><em>MOD. ${a[3]}</em></div>`).join('')}</div><h3>CARACTERÍSTICAS DA RAÇA</h3><p class="center">• Visão no escuro &nbsp;&nbsp; • Percepção aguçada<br/>• Afinidade com a natureza</p><div class="cols"><section><h4>APARÊNCIA</h4>${['Pele: Morena clara','Cabelo: Longo','Cor do cabelo: Prateado','Olhos: Verdes','Altura: Média','Tipo físico: Atlético','Marcas: Cicatriz no rosto','Acessório: Colar com pingente','Estilo: Roupa da floresta'].map(x=>`<p>✹ ${x}</p>`).join('')}</section><section><h4>EQUIPAMENTOS</h4>${['Arco longo','Aljava com flechas','Punhal','Capa da floresta'].map(x=>`<p>⚔ ${x}</p>`).join('')}</section></div><h3>PERSONALIDADE</h3><div class="chips"><span>Observadora</span><span>Curiosa</span><span>Leal</span><span>Determinada</span></div><h3>HISTÓRIA</h3><p>Lirien cresceu nas florestas, aprendendo com os animais e com as árvores. Seu objetivo é proteger a natureza e manter o equilíbrio entre todos os seres.</p></aside>
</div><div class="bottom-nav"><span>👤 Raça</span><b></b><span>⚔ Classe</span><b></b><span class="on">🎭 Aparência</span><b></b><span>📖 História</span></div></main>`;
